print (">*< >*< >*< >*< >*< >*< >*<")
print (" Please choose an option:\n")
print ("1. Returning Customer")
print ("2. New Customer")
print ("3. Guest")
print (">*< >*< >*< >*< >*< >*< >*<")
entry = int(raw_input("Enter option:"))
while entry < 1:
    print ("Please choose option 1, 2 or 3.\n")
    print (">*< >*< >*< >*< >*< >*< >*<")
    print (" Please choose an option:")
    print ("1. Returning Customer")
    print ("2. New Customer")
    print ("3. Guest")
    print (">*< >*< >*< >*< >*< >*< >*<")
    entry = int(raw_input("Enter option:"))
while entry > 3:
    print ("Please choose option 1, 2 or 3.\n")
    print (">*< >*< >*< >*< >*< >*< >*<")
    print (" Please choose an option:")
    print ("1. Returning Customer")
    print ("2. New Customer")
    print ("3. Guest")
    print (">*< >*< >*< >*< >*< >*< >*<")
    entry = int(raw_input("Enter option:"))
if entry == 3:
    print ("Welcome! We hope to see you often!")
